---
lockFile: betix.lock
placeBet: true
cronExpression: 0 0 19 * * ?
useFibonacciForStakes: true
imageDir: img
imgTimeout: 5
waitTimeBeforeAction: 500
teamImageDir: team
siteUrl: "http://www.788-sb.com"
siteHistoryUrl: "https://members.788-sb.com/MEMBERS/Authenticated/History/Sports/Default.aspx"
imageExt: .png
browser: firefox
siteName: bet365.com
minBetStake: 0.5
sikuliMinSimilarity: 0.5
messageBoxColor: Color.ORANGE
dateFormat: dd/MM/yyyy
dateTimeFormat: "dd/MM/yyyy HH:mm:ss"
teamNameSeparator: " v "
balanceRegEx: "\\s*(.*?)\\s*BGN"
historyMatchInfoLinkRegEx: "Равен @ "
matchInfoPendingState: "Текущ"
matchInfoLoseState: "Загубен"
matchInfoWinState: "Печеливш"
matchInfoStakeRegEx: "Залог:\\s*(.*?)\\s"
matchInfoCoefficientRegEx: "Никой\\s*(.*?)\\s"
matchInfoWiningRegEx: "Залог:\\s*.*?\\sПеч.*?:\\s*(.*?)\\s"
matchInfoEventRegEx: "Равен\\s*(.*?)\\s*\\(Краен Резултат"
matchInfoDateRegEx: "Краен Резултат\\)\\s*(.*?)\\s*Никой"
matchInfoDateTimeRegEx: "Час на залога:\\s*(.*?)\\s*Принтирай"
